generateForEachPlayerSeparately: false
checkUpdateInDaysEvery: 7
height: 5
width: 3
num0: "1,1,1,1,1;1,0,0,0,1;1,1,1,1,1"
num1: "0,1,0,0,1;1,1,1,1,1;0,0,0,0,1"
num2: "1,0,1,1,1;1,0,1,0,1;1,1,1,0,1"
num3: "1,0,1,0,1;1,0,1,0,1;1,1,1,1,1"
num4: "1,1,1,0,0;0,0,1,0,0;1,1,1,1,1"
num5: "1,1,1,0,1;1,0,1,0,1;1,0,1,1,1"
num6: "1,1,1,1,1;1,0,1,0,1;1,0,1,1,1"
num7: "1,0,0,0,0;1,0,0,0,0;1,1,1,1,1"
num8: "1,1,1,1,1;1,0,1,0,1;1,1,1,1,1"
num9: "1,1,1,0,1;1,0,1,0,1;1,1,1,1,1"
num10: "0,0,0,0,0;0,1,0,1,0;0,0,0,0,0" #char colon '_:_'
num11: "0,1,1,1,1;1,0,1,0,0;0,1,1,1,1" #letter 'A'
num12: "1,1,1,1,1;1,0,1,0,0;0,1,0,0,0" #letter 'P'
num13: "0,1,1,1,1;0,0,1,0,0;0,1,1,1,1" #letter 'M'